select
        vehicle_id,
        vdmfa.vehicle_detail_id,
        year_reporting_date,
        manager_defined_style,
        vehicle_manager_company_name,
        vdv.name as vehicle_name,
        vdv.include_in_anrev_odce_quarterly_index_flag,
        multi_country_or_single_country_flag,
        target_country,
        vehicle_update_status_flag,
        vehicle_structure,
        multi_sector_or_single_sector_flag,
        target_sector,
        first_closing_year,
        vqv.gearing_of_gav,
        nav_in_usd, --as "Current NAV",
        gav_in_usd, --as "Current GAV",
        -- fees and costs fields
        fundmanagementfee_actualfees_xrvalue,
        subscriptionfee_actualfees_xrvalue,
        assetmanagementfeevehiclelevel_actualfees_xrvalue,
        propertyacquisitionfeeamortisationfortheperiod_actualfees_xrvalue,
        commitmentfee_actualfees_xrvalue,
        propertydispositionfee_actualfees_xrvalue,
        distributionfee_actualfees_xrvalue,
        financingfeedebtarrangementfee_actualfees_xrvalue,
        projectmanagementfee_actualfees_xrvalue,
        windupfees_actualfees_xrvalue,
        notspecified_actualfees_xrvalue,
        -- other cost fields
        professionalservicescosts_actualfees_xrvalue,
        vehicleadministrationcosts_actualfees_xrvalue,
        auditcosts_actualfees_xrvalue,
        valuationcosts_actualfees_xrvalue,
        debtarrangementcosts_actualfees_xrvalue,
        custodiancosts_actualfees_xrvalue,
        othermiscvehiclecosts_actualfees_xrvalue,
        vehicleformationcostsamortisationfortheperiod_actualfees_xrvalue,
        bankcharges_actualfees_xrvalue,
        deaddealcosts_actualfees_xrvalue,
        staffcostsifapplicable_actualfees_xrvalue,
        transferagentcosts_actualfees_xrvalue,
        corporateincometaxes_actualfees_xrvalue,
        deferredtaxes_actualfees_xrvalue,
        averagegav_xrvalue,
        averagenav_xrvalue,
        performancefees_actualfees_xrvalue,
        -- property costs
        externalleasingcommissions_actualfees_xrvalue,
        propertyacquisitioncosts_actualfees_xrvalue,
        propertyinsurancecosts_actualfees_xrvalue,
        propertymanagementcostsnonrechargeableportion_actualfees_xrvalue,
        repairsandmaintenancecosts_actualfees_xrvalue,
        taxesonpropertyrelatedtoactivitiesexcludingtransferofothertaxesalreadyembeddedinthefundnav_actualfees_xrvalue,
        utilitiescostsnonrechargeableportion_actualfees_xrvalue,
        othermiscellaneoussundrycosts_actualfees_xrvalue,
        internalleasingcommission_actualfees_xrvalue,
        developmentfee_actualfees_xrvalue,
        propertymanagementfee_actualfees_xrvalue,
        placementagentcosts_actualfees_xrvalue,
        otherrelatedfees_actualfees_xrvalue,
        assetmanagementfeeassetlevel_actualfees_xrvalue,
        performancefees_tgerorreer
    from dw_anrev_vehicle.vehicle_detail_mgt_fees_summary vdmfa
            join  dw_anrev_vehicle.vehicle_detail_view vdv  on vdv.detail_id = vdmfa.vehicle_detail_id
             left join {{ref('anrev_mgft_vqv_stg') }} vqv on vqv.vehicle_detail_id = vdmfa.vehicle_detail_id and year_reporting_date = year
